13-master/catalog/urls.py
from django.urls import include, path, re_path
from . import views
from django.contrib.auth import views as auth_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('user/', views.user, name='user'),
    path('register/', views.register, name='register'),
    path('browse/', views.browse_tags, name='browse'),
    path('favorites/', views.favorite, name='favorites'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('editor/', views.editor, name='editor'),
    path('analyze/', views.analyze, name='analyze'),
    path('browse/<str:tag>/', views.index_tag, name='index_tag'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('profile/<int:id>/edit', views.profile_edit, name='profile_edit'),
    path('feed/', views.feed, name='feed'),
    path('feed/<str:tag>', views.feed_tag, name='feed_tag'),
    re_path(r'^search/$', views.search, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

13-master/gruppe13/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path(r'tinymce/', include('tinymce.urls')),
]

13-master/catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from datetime import datetime
import uuid
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None

    email = models.EmailField('email address', unique=True)
    bool_is_author = models.BooleanField(default=False, help_text='Designates whether user is an author', verbose_name='Author')
    bool_is_editor = models.BooleanField(default=False, help_text='Designates whether user is an editor', verbose_name='Editor')
    bool_is_executive_editor = models.BooleanField(default=False, help_text='Designates whether user is an executive editor', verbose_name='Executive editor')

    first_name = models.CharField('first name', max_length = 30, blank=False)
    last_name = models.CharField('last name', max_length = 30, blank=False)

    bio = models.TextField(blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    profile_pic = models.ImageField(default='default_profile_pic.jpg', blank=True, max_length=300)

    favorites = models.ManyToManyField('Article', related_name='favorites', blank=True)
    subscribe_author = models.ManyToManyField('User', blank=True)
    subscribe_tag = models.ManyToManyField('Tag', related_name='subscribe_tag', blank=True)
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    objects = UserManager()
    def get_image(self):
        if not self.profile_pic:
            return '/media/default_profile_pic.jpg'
        else:
            return self.profile_pic.url

    def is_author(self):
        return self.is_superuser or self.bool_is_author

    def is_editor(self):
        return self.bool_is_executive_editor or self.bool_is_editor or self.is_superuser

    def is_executive_editor(self):
        return self.is_superuser or self.bool_is_executive_editor

    def is_admin(self):
        return self.is_superuser

    def name(self):
        return self.first_name + " " + self.last_name

    def __str__(self):
        return self.first_name + " " + self.last_name


class Tag(models.Model):
    name = models.CharField(unique=True, max_length=20)

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ManyToManyField(User, related_name='author', limit_choices_to={'bool_is_author': True}, blank=True)
    title = models.CharField(max_length=100)
    text = models.TextField(default='Start typing here...')
    thumb = models.ImageField(default='default.png', blank=True, max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag, related_name='article_tag', blank=True)
    layout_choices = (('LO1', 'Normal'),
             ('LO2', 'Two columns'),
             ('LO3', 'Picture in middle'))
    layout = models.CharField(max_length=3, choices=layout_choices,default='LO1')
    is_published = models.BooleanField(default=False, help_text='Publish article')
    is_reviewed = models.BooleanField(default=False, help_text='Review article')
    assigned_proof_read = models.ManyToManyField(User, related_name="proof_read", limit_choices_to={'bool_is_editor': True}, blank = True)
    last_edited = models.DateTimeField(auto_now=True, blank=True)

    def get_image(self):
        if not self.thumb:
            return '/media/default.png'
        else:
            return self.thumb.url

    class Meta:
        ordering = ['-pub_date', ]

    def submit(self):
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class RateComment(models.Model):
    post = models.ForeignKey(Article, related_name='ratecomments', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    rating = IntegerField("Rating 1-10",
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ]
     )

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    role_choices = (
        ('', 'Request new role'),
        ('author', 'Author'),
        ('editor', 'Editor'),
        ('edit_and_author', 'Editor and author' ),
        ('exec', 'Executive editor'),
    )
    role = models.CharField(max_length=30, choices=role_choices, default='1')

    def __str__(self):
        return '{} {} requested {}'.format(self.user.first_name, self.user.last_name, self.role)


class ColorScheme(models.Model):
    color = models.CharField(max_length=100);

    @classmethod
    def create(cls, color):
        color = cls(color=color)
        return color

    def __str__(self):
        return self.color

class Layout(models.Model):
    one_column = 'layout_one_column.html'
    two_columns = 'layout_articles_side_by_side.html'
    big_two_columns = 'layout_big_article.html'
    layout_choices = ((one_column, 'One column'),( two_columns , 'Two columns'), (big_two_columns,'Big two columns'))
    layout = models.CharField(max_length=33, choices=layout_choices, default=one_column)

    def __str__(self):
        return self.layout

13-master/catalog/forms.py
from django import forms
from .models import Article, User, Tag
from django.contrib.auth.forms import UserCreationForm
from catalog.models import User, Comment, RateComment, ColorScheme, Layout, Request




class PostFormNew(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'text', 'author', 'thumb', 'layout', 'tag')


class PostFormEdit(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'text', 'author', 'thumb', 'layout', 'tag', 'is_published','assigned_proof_read', 'is_reviewed' )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        super(PostFormEdit, self).__init__(*args, **kwargs)

        if not request.user.is_executive_editor():
            del self.fields['assigned_proof_read']
            del self.fields['is_published']

            if request.user.is_author():
                del self.fields['is_reviewed']



class RegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')


class EditUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'profile_pic','bio',)


class EditorForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('is_published',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class RateCommentForm(forms.ModelForm):
    class Meta:
        model = RateComment
        fields = ('name', 'email', 'body', 'rating')

class CreateTagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name',)


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('role',)

class ColorForm(forms.ModelForm):
    class Meta:
        model = ColorScheme
        fields = ('color',)

class LayoutForm(forms.ModelForm):
    class Meta:
        model = Layout
        fields = ('layout',)

13-master/catalog/templates/analyze.html
{% extends "base_template.html" %}
{% block head %}
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css rel="stylesheet"/>
{% endblock %}
{% block css %}
    .fa-check {
        color:#4BB543;
    }
    .table-row-link {
        cursor:pointer;
    }
{% endblock %}
{% block content %}
<div class="user-stats">
    <h1>Registered users</h1>
    <table class="table table-sm table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Published</th>
                <th>Following</th>
                <th>Sub to tag</th>
                <th>Favorites</th>
                <th>Author</th>
                <th>Editor</th>
                <th>Exec</th>
            </tr>
        </thead>
    {% for u in users %}
        <tr class="table-row-link" data-href="{% url 'profile' id=u.id%}" >
            <th>{{forloop.counter}}</th>
            <td>{{u.name}}</td>
            <td>{{u.num_articles}}</td>
            <td>{{u.num_following}}</td>
            <td>{{u.num_tag}}</td>
            <td>{{u.favorites.all.count}}</td>
            <td>{%if u.is_author%} <span  class="fas fa-check"></span>{% endif %}</td>
            <td>{%if u.is_editor%} <span  class="fas fa-check"></span>{% endif %}</td>
            <td>{%if u.is_executive_editor%} <span  class="fas fa-check"></span>{% endif %}</td>
        </tr>
    {% endfor %}
    </table>
</div>
<br>
<hr>
<br>
<div class="article-stats">
    <h1>Articles</h1>
    <table class="table table-sm table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Avg. rating</th>
                <th>Comments</th>
                <th>Favorites</th>
                <th>Published</th>
                <th>Reviewed</th>
            </tr>
        </thead>
        <thead>
             <tr>
                <th>Averages:</th>
                <th></th>
                <th>{{ avg_rating_all.ratecomments__rating__avg | floatformat:2 }}</th>
                <th>{{ avg_comments_all  | floatformat:2 }}</th>
                <th>{{ avg_favorites_all | floatformat:2 }}</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    {% for a in articles %}
        <tr class="table-row-link" data-href="{% url 'post_detail' pk=a.id%}" >
            <th>{{forloop.counter}}</th>
            <td>{{a.title}}</td>
            <td>{% if a.avg_rating == None %} 0 {% else %} {{a.avg_rating}} {% endif %}</td>
            <td>{{a.num_comments}}</td>
            <td>{{a.num_favorites}}</td>
            <td>{%if a.is_published%}{{a.last_edited|date:"d/m-y H:i"}}{% endif %}</td>
            <td class="clickable-row">{%if a.is_reviewed%} <span  class="fas fa-check"></span>{% endif %}</td>
        </tr>
    {% endfor %}
    </table>
</div>
<div class="tag-stats" style="width:50%">
    <h1>Tags</h1>
    <table class="table table-sm table-hover table-striped";>
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Subscribers</th>
                <th>Published Articles</th>
            </tr>
        </thead>
         <thead>
             <tr>
                <th>Averages:</th>
                <th></th>
                <th>{{ avg_tag_all | floatformat:2 }}</th>
                <th>{{ avg_tag_all | floatformat:2 }}</th>
            </tr>
        </thead>
    {% for t in tags %}
        <tr class="table-row-link" data-href="{% url 'index_tag' tag=t.name %}" >
            <th>{{forloop.counter}}</th>
            <td>{{t.name}}</td>
            <td>{{t.num_subs}}</td>
            <td>{{t.num_articles}}</td>
        </tr>
    {% endfor %}
    </table>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('table.table').DataTable();

        $(".table-row-link").click(function() {
        window.location = $(this).data("href");
    } );
    });
</script>
{% endblock %}

13-master/catalog/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
    {% block head %}
    {% endblock %}
    <style>
        html {
          position:relative;
          min-height: 100%;
          background-color: whitesmoke;
        }
        nav {
            width:100%;
        }
        body {
          margin-bottom: 80px; /* Margin bottom by footer height */
          background-color: whitesmoke;

        }
        .footer {
          position: absolute;
          bottom: 0;
          width: 100%;
          height: 60px; /* Set the fixed height of the footer here */
          line-height: 60px; /* Vertically center the text there */
          background-color: #a3a3a3;
          left:0px;
        }

        .content{
            width: 80%;
            margin: 10px auto;
        }
        .btnSearch {
            margin-left: -50px;
            border-radius: 0px 4px 4px 0px;
        }
        .txtSearch {
            width:100%;
        }
        .btnSearch: focus-within + .btnSearch{
            visibility: visible;
        }
        .navWrapper {
            width:100%;
            padding-right:10%;
            padding-left: 10%;
        }
        a:hover {
            text-decoration:none;
        }
        a {
            text-decoration:none;
        }

        {%load color_tag%}
        {%get_colors%}
        {{css}}



        {% block css %}
        {% endblock %}
    </style>
</head>

<body>
    <nav id="hei" class="navbar navbar-expand-lg navbar-dark bg-dark" >
        <div class="class = navbar-nav navWrapper">
            <div class="navbar-nav">
                <a href="{% url 'index' %}"class="navbar-brand" ><span class="fab fa-accessible-icon"></span> Gruppe13</a>
                <a href="{% url 'index' %}" class="navbar-item nav-link active" >Home</a>
                <a href="{%url 'browse' %}" class="navbar-item nav-link mr-auto" >Browse</a>
                {% if user.is_authenticated %}
                <a href="{%url 'favorites' %}" class="navbar-item nav-link mr-auto" >Favorites</a>
                <a href="{%url 'feed' %}" class="navbar-item nav-link mr-auto" >Feed</a>
                {% endif %}
                {% if user.is_author %}
                <a href="{%url 'post_new' %}" class="navbar-item nav-link mr-auto" >New Article</a>
                {% endif %}
                {% if user.is_editor or user.is_author %}
                <a href="{%url 'editor' %}" class="navbar-item nav-link mr-auto" >Edit Article</a>
                {% endif %}
                {% if user.is_executive_editor %}
                <a href="{%url 'analyze' %}" class="navbar-item nav-link mr-auto" >Stats</a>
                {% endif %}
                {% if user.is_superuser %}
                <a href="../../../admin" class="navbar-item nav-link mr-auto" >Admin</a>
                {% endif %}
                <span class="navbar-item nav-link mr-auto" style="min-width:150px;"></span>
                <form class="form-inline" method="GET" action="{% url 'search' %}">
                    <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-primary my-2 my-sm-0 btnSearch" type="submit"><span class="fas fa-search"></span></button>
                </form>


            </div>

            <div class="nav navbar-nav navbar-right ml-auto">
                {% if user.is_authenticated %}
                <a href="{% url 'profile' id=user.id %}" class="navbar-item nav-link"></span> {{user.first_name}}</a>
                <a href="{% url 'logout' %}?next={{request.path}}" class="navbar-item nav-link"><span class="fas fa-sign-in-alt"></span> Logout</a>
                {% else %}
                <a href="{% url 'register' %}" class="navbar-item nav-link"><span class="fas fa-user-plus"></span> Sign up</a>
                <a href="{% url 'login' %}?next={{request.path}}" class="navbar-item nav-link"><span class="fas fa-sign-in-alt"></span> Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div>
        <a href="{% url 'post_new' %}"></a>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="footer">
      <div class="container">
        <span style="color:white;">Gruppe 13  <span class="far fa-copyright"></span>2018-2018</span>
      </div>
    </footer>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
</body>
</html>

13-master/catalog/templates/browse_tags.html
{% extends "base_template.html" %}

{%block css%}
    .linkstyle {
        margin-top: 10px;
        height: auto;
        width: 200px;
    }

    .row{
        margin-top: 5vh;
    }
    .col{
        max-width: 200px;
        margin:10px;


    }
    .content{
        max-width:750px;
        width: 100%;
    }

{%endblock%}
{% block content %}
    <div class="container">
    {% for tag in tags %}
        {%if forloop.counter0|divisibleby:"3"%}
            <div class="row">
        {%endif%}
                <div class="col">
                    <a class="btn btn-primary linkstyle" href="{% url 'index_tag' tag=tag.name %}">{{tag}}</a>
                </div>
        {%if forloop.counter|divisibleby:"3" or forloop.last%}
            </div>
        {%endif%}

    {% endfor %}

    {% if user.is_executive_editor or user.is_superuser %}
    <div class="row">
        <form method="POST" class="">
            <fieldset>
                <legend>Add new tag</legend>
                {% csrf_token %}
                <span class="error">{{form.name.errors}}</span>
                {{ form.name }}
                <div class="">
                    <button type="submit" class="btn btn-outline-info">Submit</button>
                </div>
            </fieldset>
        </form>
        <script>
            document.getElementById("id_name").placeholder="Tag name";
        </script>
    </div>
    {% endif %}
    </div>

{% endblock %}

13-master/catalog/templates/edit_profile.html
{% extends 'base_template.html' %}
{% block css %}
    .formWrapper {
        margin: 10px auto 0 auto;
        width: 50%;
        max-width:300px;
    }
    input[type=text] {
        width:300px;
    }
{% endblock %}

{% block content %}
    <div class="formWrapper">
    <form method="POST" class="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div class="postbutton">
        <button type="submit" class="btnSubmit">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

13-master/catalog/templates/editor.html
{% extends "base_template.html" %}

{% block title %}Home{% endblock %}

{% block css %}
    .article-wrapper {
        overflow: hidden;
        max-width: 600px;
        margin: 0 auto 10px auto;
        padding: 10px 30px 0 30px;
        background-color: white;
        border: 1px solid;
        border-color: lightgray;
        border-radius: 5px;

    }

{% endblock %}

{% block content %}
{% for article in articles %}
    {% if not article.is_published %}
            <div class="article-wrapper">
                <a style="color:black;" href="{% url 'post_detail' pk=article.id%}">
                    {% if article.is_reviewed %}
                    <h1 style="color:green">{{article.title}}</h1>
                    {% else %}
                    <h1 style="color:red">{{article.title}}</h1>
                    {% endif %}
                    <p>
                            {{article.text|safe|truncatewords:50}}
                    </p>
                    <p>Assigned for proofreading:
                    {% for proof_reader in article.assigned_proof_read.all %} {{proof_reader}},
                    {%endfor%}
                    </p>
                </a>
                {% for tag in article.tag.all %}
                    <a href="{% url 'index_tag' tag=tag %}" style="color:gray;"><span class="fa fa-tag"></span> {{ tag.name }} </a>
                {% endfor %}
                <form method="POST">
                    {{ form }}
                </form>
                <br>
            </div>
    {% endif %}
{% endfor %}
{% endblock %}

13-master/catalog/templates/favourite_list.html
{% extends "base_template.html" %}

{% block title %}Home{% endblock %}

{% block css %}
    .article-wrapper {
        max-width: 600px;
        margin: 0 auto 10px auto;
        padding: 10px 30px 0 30px;
        background-color: white;
        border: 1px solid;
        border-color: lightgray;
        border-radius: 5px;
    }
    .authors {
        font-size:13px;
    }
    a {
        color:black;
    }
{% endblock %}

{% block content %}
{% if not articles%}
<h3>No articles in favorite list</h3>
{%endif%}
{% for article in articles %}
    {% if article.is_published %}
        <div class="article-wrapper">
            <a href=" {% url 'post_detail' pk=article.id %} "> <h1>{{article.title}}</h1></a>


                <p class="authors"> Published {{ article.pub_date }} <br>
                    {% for author in article.author.all %}
                        {% if author.first_name != "" %}
                    <a href="{% url 'profile' id=author.id %}">{{ author.first_name }}</a>,
                        {% endif %}
                    {% endfor %}
                </p>
                <img src="{{article.thumb.url}}" style="max-width: 30%; height:auto;"/>
                <p>
                         <a href=" {% url 'post_detail' pk=article.id %} ">   {{article.text|safe|truncatewords:50}}</a>
                </p>
            {% for tag in article.tag.all %}
                <a href="../{{tag.id}}" style="color:gray;"><span class="fa fa-tag"></span> {{ tag }} </a>
            {% endfor %}
            <br>
            <br>
        </div>

{% endif %}
{% endfor %}
{% endblock %}

13-master/catalog/templates/profile.html
{% extends 'base_template.html' %}

{% block css %}
    .articleWrapper {
        max-width: 600px;
        padding: 10px 30px 0 30px;
        background-color: white;
        border: 1px solid;
        border-color: lightgray;
        border-radius: 5px;
        margin: 0 0 20px 0;
        overflow: hidden;
    }
    .sidebarWrapper {
        height: 100%;
        width:250px;
        position:fixed;
        margin-left:-250px;
        overflow-y: auto;
        z-index: 10;
        padding: 0 0 0 4px;
    }
    .wrapper {
        margin: 0 auto 10px auto;
        max-width: 600px;
        padding-left: -250px;
    }
    .imgProfilePic {
        border-radius: 50%;
        border: 2px solid;
    }
    .bio {
        background-color: white;
        border: 1px solid;
        border-color: lightgray;
        width:90%;
        padding: 4px;
    }
    a {
        color:black;
    }
    #id_role {
        margin-bottom: 3px;
        width:200px;
        height: 30px;
    }
{% endblock %}

{% block content %}
<div class="wrapper">

    <!--TODO: responsiv design -->
    <div class="sidebarWrapper">
        <img class="imgProfilePic" src="{{u.get_image}}" width="200px" height="200px">
        <br><br>
        {% if u == user %}
        <a href="{% url 'profile_edit' id=user.id %}" class="btn btn-outline"><span class="fas fa-user-edit"></span> Edit profile</a>
        {% endif %}
       <div class="requestForm">
            {% if request_form and u == user%}
                <form method="post">
                    {{ request_form.role }}
                    {% csrf_token %}
                    <p><button class="btn btn-outline-info"type="submit">Send request</button></p>
                </form>
            <script type="text/javascript">
                document.getElementById("id_role").options[0].disabled=true;
            </script>
            {%  endif %}
        </div>
        <h4>{{u.name}}</h4>
        <form method="POST">
                {% csrf_token %}
                {% if u in user.subscribe_author.all %}
                    <input type="submit" value="Unsubscribe" name="unsubscribe" class="favorite btn btn-outline-danger"></input>
                {% else %}
                    <input type="submit" value="Subscribe" name="subscribe" class="favorite btn btn-outline-success"></input>
                {% endif %}
        </form>
        <p class="bio">{{u.bio}}</p>
        <h5>Roles:</h5>
        <ul>
            {% if u.is_superuser %}
            <li>Admin</li>
            {% elif u.is_executive_editor %}
            <li>Executive editor</li>
            {% elif u.is_editor %}
            <li>Editor</li>
            {% endif %}
            {% if u.is_author %}
            <li>Author</li>
            {% endif %}
        </ul>
        <h5>Articles published: {{users_articles.count}}</h5>
    </div>

    <div>
        {% for article in users_articles %}
            <div class="articleWrapper">
                <a href="{% url 'post_detail' pk=article.id %}"><h3>{{article.title}}</h3></a>
                <p style="font-size: 10px;">{{article.pub_date}}</p>
                <hr>
                <a href="{% url 'post_detail' pk=article.id %}"><p>{{article.text | truncatewords:100 |safe}}</p></a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}